version: 2
# Tell CircleCI to use this workflow
workflows:
  version: 2
  default:
    jobs:
      - "test-build"


jobs:

  "test-build":
    docker:
      - image: circleci/python:3.7

    steps:

      # Get our data and merge with upstream
      - checkout

      - run:
          name: Install dependencies
          command: pip install pytest --user && pip install -e . --user
      - run:
          command: pytest --junitxml=test-reports/junit.xml --verbose
